### ISSUE TITLE
怎么将点击的index传出来，要是标签下页面样式都是一样的话，需要创建那么多VC么。

### ISSUE THREAD

**Issue by lemontree9527** [RamWire/NinaPagerView#1]

**Comment by RamWire** [comment]
可以通过设置代理来实现，你可以根据框架里的NinaBaseView中touchAction方法进行设置，我以后也会应该会加入传出index的代理；如果样式一样的话，创建那么多VC确实是一个问题，当时考虑的是如果每个界面需要下拉刷新上拉加载的情况需要控制器来完成，所以才优先考虑创建控制器，如果单纯创建view也是可行的，用一个控制器来管理它们各自的事件,不过代码会显得臃肿。

**Comment by RamWire** [comment]
已加入，现在可以在加载NinaPagerView的控制器中拿到上方点击的index。
