### ISSUE TITLE
您好，我刚测试了您的切换框架

### ISSUE THREAD

**Issue by xuhengmao** [RamWire/NinaPagerView#13]
ios8.3 发现添加到view上时，选项卡可以上下拖动

**Comment by RamWire** [comment]
您在其他版本测试会出现此问题吗？

**Comment by xuhengmao** [comment]
我这边8.0 也会出现这种情况  不知道什么原因 我想知道是不是需要设置什么属性之类的

**Comment by xuhengmao** [comment]
作者你有联系方式吗   我qq10048892  方便的话可以添加看看

**Comment by RamWire** [comment]
已解决。
