### ISSUE TITLE
看了一下你的demo，viewNumArray数组干嘛用的？

### ISSUE THREAD

**Issue by hanlsu** [RamWire/NinaPagerView#14]
为什么添加tableview后滑动，cell消失，是因为没有强引用那个视图控制器，你把以前的demo的VC使用storyboard 创建一样不会出现，maybe you should reference this document to understand view controller container,https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html     ，I think this demo need more  optimize.

**Comment by RamWire** [comment]
确实是这个原因。
