### ISSUE TITLE
在Viewcontroller中添加一个表格，发现上下滑动一下，表格内容就消失了，没找到什么原因，在原代码中添加了下，发现也是这种情况，如果只加lab没问题，加表格就出问题，是和滚动视图有冲突还是？请指教！

### ISSUE THREAD

**Issue by HeJiangWei** [RamWire/NinaPagerView#15]
在Viewcontroller中添加一个表格，发现上下滑动一下，表格内容就消失了，没找到什么原因，在原代码中添加了下，发现也是这种情况，如果只加lab没问题，加表格就出问题，是和滚动视图有冲突还是？请指教！

**Comment by RamWire** [comment]
您下载的是最新的框架吗？最新版应该已修复此问题。
