### ISSUE TITLE
拖动bug的补充

### ISSUE THREAD

**Issue by lahala** [RamWire/NinaPagerView#19]
发生此BUG的情况是在 根控制器为tabbar时  会出现 ，如果不是tab的话就不会出现
![snip20160513_3](https://cloud.githubusercontent.com/assets/9395580/15243698/cf8181b6-192f-11e6-863e-084a9a38ad31.png)

**Comment by RamWire** [comment]
您好，收到了您的邮件，能否麻烦把具体代码发我邮箱？这样对于问题的解决应该会有帮助:)

**Comment by lahala** [comment]
就在你的代码里改成 tab为根控制器 就会出现了
如截图

**Comment by lahala** [comment]
你看我的截图 就只是改了你的代码的根控制器  把导航控制器改为了 tab

**Comment by lahala** [comment]
你试试 马上就会出现我说的 BUG  本来也想着试着 修复的 ，可是能力不足，所以麻烦你 修复下咯 谢谢

**Comment by RamWire** [comment]
好的，我尽量帮您解决:)

**Comment by lahala** [comment]
嗯呢  我会时刻关注你的动态的 ，最后，真心觉得你的这个库 非常好，，赞👍

**Comment by lahala** [comment]
不知道 大神库主 发现了这个bug??还是发现了 正在修复？？

**Comment by RamWire** [comment]
我这里使用tabbar进行了测试，并没有发现您所说的拖动错误:(

**Comment by lahala** [comment]
我把 源码发你到邮箱里 ok??你再运行下看看

**Comment by RamWire** [comment]
可以

**Comment by lahala** [comment]
已发 ，基本就是源码  就改了 根控制器

**Comment by lahala** [comment]
![snip20160516_1](https://cloud.githubusercontent.com/assets/9395580/15278613/815bc60c-1b4d-11e6-9282-e3367bd51cb4.png)

**Comment by lahala** [comment]
这是bug图

**Comment by lahala** [comment]
一个录制的bug视频 刚发你邮箱了

**Comment by lahala** [comment]
我这边是可以确定 肯定有这个bug存在的

**Comment by RamWire** [comment]
解决的包已经发到您的邮箱，这确实是一个问题，解决的代价是您现在不可以随意拖动上方的toptab。

**Comment by lahala** [comment]
亲 没有收到附件 麻烦再发一下 可以吗？

**Comment by lahala** [comment]
收到啦 感谢哈 ，非常赞的大神 给你3点32个赞👍👍

**Comment by RamWire** [comment]
这确实是个bug，下个版本会对此进行修复,感谢您的反馈:)
