### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by HouWan** [RamWire/NinaPagerView#26]
一：设置 sliderHeight 之后（2和3都会出现），tab底部滚动条会出现好像是标题的倒影一样，不知道这是原本设计还是问题。
代码只是在你的Demo上多加：
    ninaPagerView.underlineColor = COLOR(152.0, 221.0, 89.0, 1.0);
    ninaPagerView.sliderHeight = 3.0 ;
如图：
![image](https://cloud.githubusercontent.com/assets/13991710/19593040/233c8378-97b1-11e6-9f84-1ca13d42ef42.png)

二：NinaPagerView.m 类，第180行
self.viewController.navigationController.navigationBar.translucent = NO;
这句我觉得应该研究下加的时机或者加的判断，在我的Demo里，如果把这句注释掉，就会正常，如果运行，则会出现下面的情况：
创建之后，进入页面会没有按照frame设置的效果，顶部出现一段距离，但是一点，或者滑动，就会恢复过来。
如图：
![image](https://cloud.githubusercontent.com/assets/13991710/19593272/5634dd9c-97b2-11e6-91ed-4b31fb50eff6.png)

**Comment by RamWire** [comment]
您好，最近框架相比于原来做了比较大的改动所以可能出现了一系列的问题，所以感谢您的反馈。
第一个问题：sliderHeight这个属性当初在写的时候是把它和NinaPagerStyleSlideBlock这个模式相配套的，所以当时并没有考虑使用者在使用的过程中在其他的样式中使用它出现的问题。您上面提到的问题在最新的更新中已经修复。
第二个问题：这句确实是原来我没有把它设置在框架中的，后来改版之后加入的，为了防止整体view上移。能具体说一下您有设置导航栏的其他属性吗，或者是NinaPagerView的纵坐标是0吗？

**Comment by xinqin2496** [comment]
我循环添加5个webView控制器的时候,直接崩溃bool _WebTryThreadLock(bool), 0x600000205440: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...

**Comment by RamWire** [comment]
Reopen if necessary.
