### ISSUE TITLE
学习

### ISSUE THREAD

**Issue by HouWan** [RamWire/NinaPagerView#27]
挺喜欢这个框架的，虽然里面有注释，但是如果有博客讲解一下原理就好了，比如各个类之间的关系？
缓存的策略？  KVO的策略？

**Comment by RamWire** [comment]
感谢反馈，最近因为工作的缘故可能暂时没法通过博客进行讲解，不过之后会补上:)

**Comment by RamWire** [comment]
感谢反馈，如果不忙的时候我会尽力写一下:)


Sent from Mail Master
在2016年10月21日 17:21，HouWan 写道:

挺喜欢这个框架的，虽然里面有注释，但是如果有博客讲解一下原理就好了，比如各个类之间的关系？
缓存的策略？ KVO的策略？
