### ISSUE TITLE
Top menu scrolling with content

### ISSUE THREAD

**Issue by ac1dpax** [RamWire/NinaPagerView#28]
Is there a possible to scroll top menu with content?

**Comment by RamWire** [comment]
Currently not support this function,but I'll add it in the future:)

**Comment by RamWire** [comment]
Done.

**Comment by ac1dpax** [comment]
I downloaded latest files, in example added: 
ninaPagerView.nina_scrollEnabled = YES; 

but top menu always stay on top, did not scroll up with content, do I do something wrong?

**Comment by RamWire** [comment]
S

**Comment by RamWire** [comment]
Sorry,I might not understand the meaning of your first sentences.You mean you wanna to scroll top menu up and down?

**Comment by ac1dpax** [comment]
I mean when scroll table content down, menu goes with content up off the screen, not staying always on top.

**Comment by RamWire** [comment]
I understand.It's a good idea,I will try to work it out in the future:)

**Comment by ac1dpax** [comment]
Nice!! Many thx!

**Comment by RamWire** [comment]
Done.

**Comment by ac1dpax** [comment]
Nicely done!

**Comment by ac1dpax** [comment]
Can you please help me to add on top of menu custom information from another viewcontroller and I want that information scrolls away with menu?
