### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by yubowen04551** [RamWire/NinaPagerView#29]
我遇到一个问题,我需要从一个navigation bar是透明的控制器push到NinaPageView的控制器,因为设置了self.navigationController.navigationBar.translucent = NO;  在pop回来的时候我的透明的navigation bar变成了白色而且布局也从(0,64)开始计算了 请问有什么解决的办法吗?

**Comment by RamWire** [comment]
不设置self.navigationController.navigationBar.translucent = NO的话试试看？把NinaPagerView的坐标相应改变一下怎么样？

**Comment by yubowen04551** [comment]
非常感谢您的回答, 我已经按照您说的方法注释掉了NinaPageView.m里面的self.navigationController.navigationBar.translucent = NO,并把坐标调成(0,64),这样解决了之前的问题;
但是新的问题出现了 , NinaPageView上面的Button不见了 变成了一条白色的View

**Comment by RamWire** [comment]
这个确实是我的疏忽，很抱歉，您可以尝试在创建NinaPagerView的控制器中加入self.edgesForExtendedLayout = UIRectEdgeNone;试一下，我这边测试应该是没有问题了。

**Comment by yubowen04551** [comment]
再次感谢您的解答, 问题已经解决了,十分感谢

**Comment by RamWire** [comment]
别客气，感谢反馈，我之后会将这个问题修复好。
