### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by SinAlfa** [RamWire/NinaPagerView#3]
您这个示例工程文件里的那个ninapageview文件夹添加到我的个人工程中之后根本没法用 全部是野指针错误 。。。。就是完全按照你写的步弄得：导入工程  ，引进头文件   创建需要的三个数组  实例化最后添加到self.view 可是 然并卵啊。。。。。  自己新建了文件测试 也都是野指针错误。。。bad_access....迷醉了。。。求助啊！

**Comment by RamWire** [comment]
已解决。
