### ISSUE TITLE
Title crop and icon size

### ISSUE THREAD

**Issue by ac1dpax** [RamWire/NinaPagerView#31]
Hi, how can be prevent menu title cropping? And how can I change title font and icon sizes? 
![snap](https://cloud.githubusercontent.com/assets/1861324/20558779/6bb0c898-b17a-11e6-852e-b655b1c0520d.jpg)

**Comment by RamWire** [comment]
It's just an example,You can design your own view and change font and image size.

**Comment by ac1dpax** [comment]
Please can you point me to file where it is can be done?

**Comment by RamWire** [comment]
You can create view like TopTabView in Example.

**Comment by ac1dpax** [comment]
Oh, didn't notice that view, thank you!
