### ISSUE TITLE
关于子控制器里View的生命周期方法

### ISSUE THREAD

**Issue by HouWan** [RamWire/NinaPagerView#33]
目前， 我发现此框架，来回切换子控制器的话，并不会来回调用
viewWillAppear:
viewWillDisappear:
....
等View显示过程的生命周期方法，大神有时间研究一下呗，看能否利用运行时，KVO之类的切换自控制器时，也会对应的调用View的几个方法。

**Comment by RamWire** [comment]
确实不会调用，如果想通过切换子控制器进行实时的变化的话，现阶段只能用代理方法- (void)ninaCurrentPageIndex:(NSString *)currentPage来实现。
