### ISSUE TITLE
在有navigationBar的情况下，会出现如下bug

### ISSUE THREAD

**Issue by yjjwxy2** [RamWire/NinaPagerView#36]
一开始顶部标签的位置会在(0,0)这个位置，过了1s之后才回到(0,64)这个位置。会出现一开始进去之后是没有标签栏的，然后闪一下再出现标签栏。pagerView的frame我设置是CGRectMake(0, 0, KscreenWidth, KscreenHeight)。如果换成CGRectMake(0, 64, KscreenWidth, KscreenHeight)，刚进去正常(在navigationBar下面)，1s之后又会下移64，出现了空白区域。看到后请尽快回复，谢谢

**Comment by RamWire** [comment]
有尝试过在真机上测试吗？

**Comment by yjjwxy2** [comment]
已经解决了
