### ISSUE TITLE
有关编辑tab的相关问题

### ISSUE THREAD

**Issue by yansun2006** [RamWire/NinaPagerView#37]
因项目中有需要加入编辑tab的功能，类似今日头条，点击"+"进入编辑tab的功能。
一般编辑完成后 (NSArray *)titles、(NSArray *)childVCs会发送变化。对于tab数据变化后，如何更新NinaPagerView视图？现在我这边就是重新初始化NinaPagerView

第二个问题
能否通过代码的方式选中tab项？现在看下来只有初始化后设置ninaDefaultPage的功能。
因为在某些情况下需要手动选中tab项，比如上面的编辑功能，进入编辑页面后，但是没有改变tab项，只是在编辑页面选中一个tab然后返回到包含这个NinaPagerView的控制器，这时需要选中该tab。

**Comment by RamWire** [comment]
第一个问题的话暂时只能重新初始化来解决，以后我会考虑加入此功能。
第二个问题也暂时不支持，抱歉。

**Comment by yansun2006** [comment]
谢谢及时的回复

**Comment by RamWire** [comment]
客气了。

**Comment by RamWire** [comment]
新增reload方法来对issue中的第一个问题进行解决，如果您有兴趣麻烦帮忙测试一下，+号的话以后进行添加:)

**Comment by yansun2006** [comment]
好的

**Comment by RamWire** [comment]
第二个问题已加入ninaChosenPage属性，可以实时对tab进行选择，希望能满足您的需求:)
