### ISSUE TITLE
tableview创建后消失的bug怎么解决啊，怎么将tableview子类化，新手求教

### ISSUE THREAD

**Issue by zhouhang163** [RamWire/NinaPagerView#4]
谢谢

**Comment by RamWire** [comment]
你好，请看Example中的FirstTableView的实现:)

**Comment by zhouhang163** [comment]
谢谢，我看的是您在code4app上面的例子，没有这个- -

**Comment by RamWire** [comment]
嗯，GitHub上的是最新代码，也修复完善了一些错误:)

**Comment by zhouhang163** [comment]
还是有一些问题，我想请教您一下，您qq多少啊

**Comment by zhouhang163** [comment]
就是我想跳转界面的是，再tableview得子类里面无法实现跳转啊，因为tableview的子类中无法使用[self.navigationController pushViewController:moreVc animated:YES];这个方法啊- -

**Comment by RamWire** [comment]
您好，如果想在view中实现控制器的跳转可以使用代理或者您可以去我的另一个框架NinaCycleBannerView中找到UIView+ViewController的Category，即可实现。

**Comment by zhouhang163** [comment]
好的，谢谢您，但还是希望您能解决这个bug，让tableview可以写在viewcontroller里面

**Comment by RamWire** [comment]
好的，感谢反馈:)

**Comment by RamWire** [comment]
已解决反馈的TableView问题，pod已更新至0.4.1:)

**Comment by zhouhang163** [comment]
[self.navigationController pushViewController:lrVC animated:YES];跳转界面的方法不好用了。。。

**Comment by zhouhang163** [comment]
您的这个框架真的挺好用的，简单易用，但不能跳转这个bug真是。。。

**Comment by zhouhang163** [comment]
不光是tableview上点击cell不能跳转，我随便写一个按钮同样不能跳转啊

**Comment by RamWire** [comment]
这个问题刚才修复了，具体请看新的README，感谢您的反馈。

**Comment by zhouhang163** [comment]
我更新到0.4.2版本了，普通按钮的可以跳转界面了，但是轻拍事件（图片上加的手势）和tableview的点击事件还是不能跳转那界面，只是执行了方法，但是没法跳转。。。

**Comment by RamWire** [comment]
Example中cell点击事件实现是没问题的。

**Comment by zhouhang163** [comment]
对的，我刚才看了，我这里只有在“现在是控制器1”的时候，也就是第一个子控制器里面的点击事件不好用，剩下的都没问题的，也不知道咋回事啊。。。

**Comment by zhouhang163** [comment]
https://github.com/zhouhang163/DouYuTV,我刚把我的小demo传到github上了，您要是有时间的话可以帮我看一下，谢谢，我真不知道第一个控制器为什么不能跳转

**Comment by RamWire** [comment]
您上传的demo里我没有看到涉及此框架的相应代码...您确定已经设置了'ninaPagerView.pushEnabled = YES;'这句代码吗？

**Comment by zhouhang163** [comment]
额。。。这句话好像没有写，不好意思，打扰您了。。。写上这句话就好了，谢谢您了，非常感谢

**Comment by RamWire** [comment]
没关系，感谢您的反馈:)
