### ISSUE TITLE
怎么获取滚动代理?

### ISSUE THREAD

**Issue by Jayxiang** [RamWire/NinaPagerView#40]
由于我在滚动视图上有输入框,当Controller滚动时需要隐藏掉键盘,但是滚动的方法怎么获取呢?本来想用界面将要消失的时候隐藏  发现不走这个方法...   不知道能不能获取到页面滑动时的方法.

**Comment by RamWire** [comment]
获取当前页面的方法是有的，就是代理方法ninaCurrentPageIndex:(NSString *)currentPage，不知道是否符合您的需求。

**Comment by Jayxiang** [comment]
这个也行,但是想在拖拽的时候就隐藏..我在你的代码里加了_scrollView.keyboardDismissMode = UIScrollViewKeyboardDismissModeOnDrag;   应该没有影响吧

**Comment by RamWire** [comment]
嗯，也可以把我的代理方法修改一下即可，修改一下currentpage的计算方法试试。

**Comment by Jayxiang** [comment]
问题是 如果我想用你的新版本了 那还得再改  看看能不能把一些东西扩展出来
