### ISSUE TITLE
demo的Block类型怎么跟你网页上gif的不一样？demo背景是长方形的，怎样改成椭圆形

### ISSUE THREAD

**Issue by liao10108180** [RamWire/NinaPagerView#41]

**Comment by RamWire** [comment]
请自行查看NinaPagerView注释。

**Comment by playscforever** [comment]
@liao10108180 你有解决吗

**Comment by playscforever** [comment]
@RamWire 这个常用的功能最好还是写在readme里面吧，看着好累哦

**Comment by RamWire** [comment]
@playscforever 确实应该把一些属性写在文档里，以后考虑完善文档内容。
第二个问题，注释里我觉得写的比较清楚，这个slideBlockCornerRadius其实是比例而不是直接赋值的，名称上确实应该改一下。如果想完成demo中的效果请设置slideBlockCornerRadius为2，并且sliderHeight为小于40即可。

**Comment by playscforever** [comment]
@RamWire thanks
