### ISSUE TITLE
看过代码有两个建议

### ISSUE THREAD

**Issue by Easyzhan** [RamWire/NinaPagerView#42]
第一个,滑动切换的时候可以看一下微博那个个人中心的bottomline,它是随之切换的时候先拉长后恢复长度的;
第二个,有图片和label的style,图片位置希望可以有接口暴露出来可以设置图片在文字的上下左右;
个人建议O(∩_∩)O哈！

**Comment by RamWire** [comment]
感谢您的建议，以后有时间会加上:)
