### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by niravvirpara007** [RamWire/NinaPagerView#44]
Hello RamWire,

I use your ninapagerview library .

It's working perfectly.

I want all view controllers should load every time.i don't want any caches. means viewdidload function should call every time .

Can you guide me in detail? What I have to implement for this functionality?

I hope you will guide me. Waiting for your positive response.

Thanks
Nirav.

**Comment by RamWire** [comment]
Hi Nirav,
Thanks for using NinaPagerView.
Current version of NinaPagerView is not support your requirement.
But you can finish it by Modifying the codes in NinaPagerView:
First you need go to Line 188,Line 276 and Line 351.Change the numbers from 5 to 1.
Then you need implement NinaPagerView delegate method - (BOOL)deallocVCsIfUnnecessary and return YES.
Wish to help:)
RamWire.
