### ISSUE TITLE
若加入的子VC是用IB创建的，则子VC不会显示 (viewWillAppear不会调用) 

### ISSUE THREAD

**Issue by bigship** [RamWire/NinaPagerView#5]
因为初始化方法中传入的是子vc的类名，然后框架内部自己去新创建子vc。这和用IB创建出来的vc已经不是同一个对象了。建议再提供一个初始化方法，直接传加入了子VC的实例数组进来，方便使用IB创建VC的人。

**Comment by RamWire** [comment]
感谢您提供的建议，这几天会对此方面进行改进。

**Comment by RamWire** [comment]
已改进升级:)
