### ISSUE TITLE
莫名的崩溃

### ISSUE THREAD

**Issue by GL-ZHU** [RamWire/NinaPagerView#51]
`- (NinaPagerView *)pagerView{
    if (!_pagerView) {
        CGRect rect = CGRectMake(0, 64, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height-64);
        _pagerView = [[NinaPagerView alloc] initWithFrame:rect WithTitles:self.categorys WithVCs:self.vcs];
    }
    return _pagerView;
}`
这是最基本的创建，标题数组和控制器数组都是22个。VCS里面都是控制器，但是，加载完成后，从16-21折几个控制器加载不出来，然后再pop出当前的控制器，NinaPagerView的实例，释放后，就会崩溃。

**Comment by RamWire** [comment]
暂时只测试了不超过10个的情况，再多控制器的情况可能会出现您上述所说的问题，我会有时间进行修复改进的，感谢反馈。
