### ISSUE TITLE
什么时候适配iOS11？

### ISSUE THREAD

**Issue by xuanInitial** [RamWire/NinaPagerView#53]

**Comment by RamWire** [comment]
刚才在iOS 11环境下跑了一下没怎么发现问题，请问发现了什么问题嘛？

**Comment by xuanInitial** [comment]
![img_5707](https://user-images.githubusercontent.com/20314658/30725991-eac62dd2-9f7a-11e7-81e6-3c3ca860140f.PNG)
![img_5706](https://user-images.githubusercontent.com/20314658/30725995-ee01238a-9f7a-11e7-92a3-047e64108dee.PNG)
选择第2个或者第3个切换回来就会变成这样（下面的横线跑到第一个下面了）  是我打开姿势不对吗？

**Comment by RamWire** [comment]
demo里您试过是正常的吗，如果可以请告诉我这种问题如何重现。

**Comment by xuanInitial** [comment]
我试试demo 感谢回复

**Comment by xuanInitial** [comment]
刚用demo实验了一下 也会有这个问题  我是xcode9 iOS11   运行demo  点击showControllersWithBottomLineStyle  -->点击第一个以后的菜单 -->点击详情 -->返回  问题会复现

**Comment by RamWire** [comment]
嗯，重现了，我看一下是什么情况，感谢反馈。

**Comment by RamWire** [comment]
Fixed up pod version 1.6.2.
