### ISSUE TITLE
如何只用一半的宽度

### ISSUE THREAD

**Issue by playscforever** [RamWire/NinaPagerView#54]
<img width="278" alt="default" src="https://user-images.githubusercontent.com/7533665/30954665-986638fa-a463-11e7-8e60-878b5de6a93b.png">
我只想在红色区域显示segment，其他地方都是空白，可以实现吗

**Comment by playscforever** [comment]
或者说，如何控制他们之间的间距？

**Comment by RamWire** [comment]
这个需求现在应该是不支持，抱歉:(
