### ISSUE TITLE
会自动往下偏一点

### ISSUE THREAD

**Issue by maybenai** [RamWire/NinaPagerView#59]
我在用这个的时候从A vc push 到B vc，B vc里用这个框架，但是ninaPageView会往下跳一下才正常

**Comment by ranjun93** [comment]
请问你解决了吗？ 我也遇到这个问题

**Comment by maybenai** [comment]
你设置下背景颜色试试？我是自己封装了一个简单的

**Comment by ranjun93** [comment]
谢谢了， 我解决了
