### ISSUE TITLE
您好，我在子控制器中执行隐藏tabbar的代码不好使，具体代码如下

### ISSUE THREAD

**Issue by zhouhang163** [RamWire/NinaPagerView#6]
self.hidesBottomBarWhenPushed = YES;
[self.navigationController pushViewController:adVC animated:YES];
self.hidesBottomBarWhenPushed = NO;
我在执行隐藏tabbar的这几句代码在子控制器中不好用，希望您能解决，谢谢

**Comment by RamWire** [comment]
我在自己的项目中并没有发现此问题，所以不知道您所说的是不是因为使用此框架所出现的问题。

**Comment by zhouhang163** [comment]
是您的这个问题，我在您的demo中加入了UITabBarController之后，再FirstViewController中写入代码TestViewController *testVC = [TestViewController new];
    self.hidesBottomBarWhenPushed = YES;
    [self.navigationController pushViewController:testVC animated:YES];
    self.hidesBottomBarWhenPushed = NO;
就不会隐藏下面tabbar，而在其他没有使用您的框架的ViewController中会隐藏tabbar的

**Comment by RamWire** [comment]
如果您不介意，把涉及到这个问题的代码麻烦发到我的邮箱吧。

**Comment by zhouhang163** [comment]
好的您的邮箱地址是什么

**Comment by RamWire** [comment]
zhaogengda@126.com

**Comment by zhouhang163** [comment]
demo已经发送

**Comment by RamWire** [comment]
修改过的代码已经发送到您的邮箱中，您如果想要使用hidesBottomBarWhenPushed这个属性在这个框架中，可能您需要在您要push的控制器中重写hidesBottomBarWhenPushed这个属性，具体您可参照我在ChildViewController中的写法:)

**Comment by zhouhang163** [comment]
好的，谢谢您，我试过了，已经好使了

**Comment by RamWire** [comment]
不客气，感谢反馈:)
