### ISSUE TITLE
iOS11.0-11.1BUG

### ISSUE THREAD

**Issue by lukenowre** [RamWire/NinaPagerView#60]
在iOS11.0-11.1时候在创建ninaview的时候会调用一次layoutsubviews，从子页面返回的时候又会调一次layoutsubviews，这个方法应该调一次，但是11.0-11.1会 调两次，又走了initUI的方法

**Comment by spiritbuild** [comment]
我也遇到这个问题,结果就是,从二级页面返回时,自动请求数据

**Comment by am1993421** [comment]
作者还维护吗

**Comment by RamWire** [comment]
抱歉，最近工作太忙，我使用了最近的代码在11.2下进行测试貌似没发现重复调用这个问题，请告诉我应该如何重现这个问题，谢谢。

**Comment by am1993421** [comment]
@RamWire  东西挺好用的 希望作者能继续改进哇 。现在这个- (void)ninaCurrentPageIndex:(NSInteger)currentPage currentObject:(id)currentObject lastObject:(id)lastObject 代理方法还要在子页面viewDidLoad之后 我记得之前没改这个代理方法的时候是先走这个代理再走子页面的viewDidLoad 害的我改了好多代码

**Comment by spiritbuild** [comment]
之前用的老版本,更新了1.6版本后,问题不存在了
