### ISSUE TITLE
请问一下 怎么让头部的滑块变成圆角模式

### ISSUE THREAD

**Issue by lanhaoiOS** [RamWire/NinaPagerView#61]
NinaPagerView *pageView = [[NinaPagerView alloc]initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT - SFC_NavigationBarHeight) WithTitles:titleArray WithVCs:vcsArray];
   pageView.titleScale = 1;
   pageView.ninaPagerStyles = NinaPagerStyleSlideBlock;
   pageView.slideBlockCornerRadius = 20;
   pageView.delegate = self;
   pageView.selectTitleColor = SFC_WhiteColor;
   pageView.unSelectTitleColor = SFC_RGBColor(155, 155, 155);
   pageView.sliderBlockColor = SFC_RGBColor(255, 113, 87);
   pageView.underLineHidden = true;
   [self.view addSubview:pageView];
我向这样写并没有实现圆角

**Comment by RamWire** [comment]
请看sliderCornerRadiusRatio属性的注释，并不是单纯的Radius而是按照比例进行计算的。

**Comment by lanhaoiOS** [comment]
我改好了 但是现在有个新问题 就是滑块的高度=pageView的高度 可不可以设置滑块在pageView上下的间隔
![2017-12-25 4 11 47](https://user-images.githubusercontent.com/18606137/34336033-c03caccc-e98e-11e7-8ce5-4a7dcd2c7d8b.png)
 滑块可不可以设置背景图片 不要纯颜色

**Comment by RamWire** [comment]
暂时只能设置颜色背景，您可以试试colorWithPatternImage方法看看能不能实现。上下间隔可能需要改源码实现。
