### ISSUE TITLE
push 到带有NinaPagerView的UITableViewcontroller子控制器 最后一条cell 显示一半，按要求self.navigationController.navigationBar.translucent = NO ;已设置还是不可以

### ISSUE THREAD

**Issue by dreamahui** [RamWire/NinaPagerView#66]
![image](https://user-images.githubusercontent.com/3079227/41923751-d961b6b0-799a-11e8-82eb-c08a1f410b28.png)
如提供的demo中最后一条完全不显示

**Comment by RamWire** [comment]
Solved.
