### ISSUE TITLE
原控制器视图被遮盖

### ISSUE THREAD

**Issue by novial** [RamWire/NinaPagerView#7]
您好，请问一下，为什么添加了ninaPagerView之后，原控制器上的一些视图就不见了呢。
我运行之后发现，原控制器上最下方的几个button都不见了，但是在那个位置点击还是会触发点击事件
请问有什么方法可以解决这个被遮盖的问题吗
望大神告知，谢谢

**Comment by RamWire** [comment]
您所说的原控制器是添加NinaPagerView的控制器吗，最下方的button是tabbar上的button吗？

**Comment by novial** [comment]
是添加NinaPagerView的控制器，我用xib创建的，下方的按钮不在tabBar上（这个页面隐藏了tabBar），是在xib上拖拽的控件

**Comment by RamWire** [comment]
您是想在每个子控制器中都要显示按钮吗？

**Comment by novial** [comment]
对，是这样的，所以才写在添加NinaPagerView。但是运行之后就消失了

**Comment by RamWire** [comment]
恩，这里遮盖的原因是因为当时设置scrollview高度的问题，导致viewcontroller的下方无法显示，最新代码已修改，请更新最新的试试看:)

**Comment by novial** [comment]
感谢！

**Comment by RamWire** [comment]
感谢反馈:)
