### ISSUE TITLE
跳转问题

### ISSUE THREAD

**Issue by NickyWei** [RamWire/NinaPagerView#8]
我在子的controller 创建表格，点击跳转报错reason: 'Pushing a navigation controller is not supported'
 ninaPageView.pushEnabled = YES;  这个带我我也加上了 ，需要怎样处理，谢谢

**Comment by RamWire** [comment]
您好，具体是在第一个子控制器还是其他子控制器出现此问题的呢？

**Comment by NickyWei** [comment]
不好意思，少看点东西，在子的controller 还有方法，我没写。我加上试试看，谢谢

**Comment by NickyWei** [comment]
哦哦  我跳转方法写错了  ，按照例子中的写 ok啦  谢谢

**Comment by RamWire** [comment]
好的:)
