### ISSUE TITLE
你好，问个问题

### ISSUE THREAD

**Issue by meliuxudong** [RamWire/NinaPagerView#9]
请问能在子控制器里实时修改title吗？就是菜单栏的title，比如我想加入子控制器里一些数据，有什么方法没有？

**Comment by RamWire** [comment]
您说的是主控制器的title吗？

**Comment by meliuxudong** [comment]
恩，就是最早初始化时传入的titleArray里的内容

**Comment by RamWire** [comment]
由于当时title的赋值是在初始化方法中实现的，所以实时修改title这个可能不太好实现:(

**Comment by meliuxudong** [comment]
恩，我想了一下，在NInaBaseView中你生成的buttonArray里可以取出生成的button，改对于button的title应该就可以了。写个代理应该可以。谢谢你这个三方，说实话帮我个大忙。

**Comment by RamWire** [comment]
客气了，感谢反馈，以后对这个需求进行改进:)
